[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'thinca/vim-scouter'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = "aiya000/vim-scratch-buffer"

[[plugins]]
repo = "itchyny/calendar.vim"
